[project]
name = "test-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agents>=0.0.16",
    "rich>=14.0.0",
    "tensorflow>=2.19.0",
]
